parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: joan_perello
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 12285a7e1fa0d7506300196bcdf20e7b3101c6b1
    database_path: null
